// IosPostprocess — what the generated Xcode project needs beyond Player Settings.
// Drop into Assets/Editor/ or a package's Editor/ (asmdef: includePlatforms ["Editor"]).
//
// The Xcode project is regenerated by every build, so anything added by hand is lost. This runs
// after each iOS build and is IDEMPOTENT: it only adds what is missing, never overwrites a value
// the project already set.
//
// Edit the two tables. Frameworks go on the UnityFramework target — plugin code is compiled
// there, not into the app target.
#if UNITY_IOS
using System.IO;
using UnityEditor;
using UnityEditor.Callbacks;
using UnityEditor.iOS.Xcode;
using UnityEngine;

public static class IosPostprocess
{
    // A missing usage string is not a warning: the first call into the guarded API kills the process.
    static readonly (string key, string text)[] UsageStrings =
    {
        // ("NSCameraUsageDescription", "Used to scan the marker on the controller."),
        // ("NSCameraUsageDescription",     "Used to scan the code on the box."),
    };

    static readonly string[] Frameworks =
    {
        // "CoreMotion.framework",
        // "CoreBluetooth.framework",
    };

    // e.g. "location" to keep tracking in the background. Leave empty unless the product needs it:
    // App Review asks for the reason.
    static readonly string[] BackgroundModes = { };

    [PostProcessBuild(100)]
    public static void OnPostprocessBuild(BuildTarget target, string path)
    {
        if (target != BuildTarget.iOS) return;

        string plistPath = Path.Combine(path, "Info.plist");
        if (File.Exists(plistPath))
        {
            var plist = new PlistDocument();
            plist.ReadFromFile(plistPath);
            bool dirty = false;
            foreach (var (key, text) in UsageStrings)
            {
                if (plist.root[key] != null) continue;
                plist.root.SetString(key, text);
                dirty = true;
                Debug.Log("[IosPostprocess] Info.plist + " + key);
            }
            if (BackgroundModes.Length > 0)
            {
                var arr = plist.root["UIBackgroundModes"]?.AsArray() ?? plist.root.CreateArray("UIBackgroundModes");
                foreach (var mode in BackgroundModes)
                {
                    bool has = false;
                    foreach (var v in arr.values) if (v.AsString() == mode) has = true;
                    if (has) continue;
                    arr.AddString(mode);
                    dirty = true;
                    Debug.Log("[IosPostprocess] UIBackgroundModes + " + mode);
                }
            }
            if (dirty) plist.WriteToFile(plistPath);
        }
        else Debug.LogWarning("[IosPostprocess] no Info.plist at " + plistPath);

        if (Frameworks.Length == 0) return;
        string projPath = PBXProject.GetPBXProjectPath(path);
        if (!File.Exists(projPath)) { Debug.LogWarning("[IosPostprocess] no pbxproj at " + projPath); return; }
        var proj = new PBXProject();
        proj.ReadFromFile(projPath);
        string fw = proj.GetUnityFrameworkTargetGuid();
        foreach (var f in Frameworks)
        {
            if (proj.ContainsFramework(fw, f)) continue;
            proj.AddFrameworkToProject(fw, f, false);
            Debug.Log("[IosPostprocess] UnityFramework + " + f);
        }
        proj.WriteToFile(projPath);
    }
}
#endif
